export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const PREFERRED_CATEGORIES_SAVE_REQUEST =
  "PREFERRED_CATEGORIES_SAVE_REQUEST";
export const PREFERRED_CATEGORIES_SAVE_SUCCESS =
  "PREFERRED_CATEGORIES_SAVE_SUCCESS";
export const PREFERRED_CATEGORIES_SAVE_FAIL = "PREFERRED_CATEGORIES_SAVE_FAIL";
export const PREFERRED_CATEGORIES_SAVE_RESET = "FEED_CREATE_RESET";
