export const COLOR_PRIMARY = "#8eecf5";
export const COLOR_SECONDARY = "#b9fbc0";
export const COLOR_BACKGROUND_PRIMARY = "#203040";
export const COLOR_BACKGROUND_SECONDARY = "#005f73";
/* export const COLOR_PRIMARY = '#48cae4';
export const COLOR_SECONDARY = '#64dfdf';
export const COLOR_BACKGROUND_PRIMARY = '#002137ff';
export const COLOR_BACKGROUND_SECONDARY = '#00253eff'; */
export const COLOR_WHITE = "#fff";
export const COLOR_BLACK = "#000";
export const COLOR_GRAY_LIGHT = "#e9ecef";
export const COLOR_GRAY_DARK = "#adb5bd";
export const COLOR_RED = "red";
