export const FEED_LIST_REQUEST = 'FEED_LIST_REQUEST';
export const FEED_LIST_SUCCESS = 'FEED_LIST_SUCCESS';
export const FEED_LIST_FAIL = 'FEED_LIST_FAIL';

export const FEED_CREATE_REQUEST = 'FEED_CREATE_REQUEST';
export const FEED_CREATE_SUCCESS = 'FEED_CREATE_SUCCESS';
export const FEED_CREATE_FAIL = 'FEED_CREATE_FAIL';
export const FEED_CREATE_RESET = 'FEED_CREATE_RESET';

export const FEED_UPDATE_REQUEST = 'FEED_UPDATE_REQUEST';
export const FEED_UPDATE_SUCCESS = 'FEED_UPDATE_SUCCESS';
export const FEED_UPDATE_FAIL = 'FEED_UPDATE_FAIL';

export const FEED_DELETE_REQUEST = 'FEED_DELETE_REQUEST';
export const FEED_DELETE_SUCCESS = 'FEED_DELETE_SUCCESS';
export const FEED_DELETE_FAIL = 'FEED_DELETE_FAIL';

export const INDIVIDUAL_FEED_DETAILS_REQUEST = 'INDIVIDUAL_FEED_DETAILS_REQUEST';
export const INDIVIDUAL_FEED_DETAILS_SUCCESS = 'INDIVIDUAL_FEED_DETAILS_SUCCESS';
export const INDIVIDUAL_FEED_DETAILS_FAIL = 'INDIVIDUAL_FEED_DETAILS_FAIL';

export const FEED_ANSWERS_REQUEST = 'FEED_ANSWERS_REQUEST';
export const FEED_ANSWERS_SUCCESS = 'FEED_ANSWERS_SUCCESS';
export const FEED_ANSWERS_FAIL = 'FEED_ANSWERS_FAIL';

export const ANSWER_CREATE_REQUEST = 'ANSWER_CREATE_REQUEST';
export const ANSWER_CREATE_SUCCESS = 'ANSWER_CREATE_SUCCESS';
export const ANSWER_CREATE_FAIL = 'ANSWER_CREATE_FAIL';

export const FEED_ANSWER_DELETE_REQUEST = 'FEED_ANSWER_DELETE_REQUEST';
export const FEED_ANSWER_DELETE_SUCCESS = 'FEED_ANSWER_DELETE_SUCCESS';
export const FEED_ANSWER_DELETE_FAIL = 'FEED_ANSWER_DELETE_FAIL';