export const FEED_LIST_REQUEST = 'FEED_LIST_REQUEST';
export const FEED_LIST_SUCCESS = 'FEED_LIST_SUCCESS';
export const FEED_LIST_FAIL = 'FEED_LIST_FAIL';

export const FEED_CREATE_REQUEST = 'FEED_CREATE_REQUEST';
export const FEED_CREATE_SUCCESS = 'FEED_CREATE_SUCCESS';
export const FEED_CREATE_FAIL = 'FEED_CREATE_FAIL';
export const FEED_CREATE_RESET = 'FEED_CREATE_RESET';

export const INDIVIDUAL_FEED_DETAILS_REQUEST = 'INDIVIDUAL_FEED_DETAILS_REQUEST';
export const INDIVIDUAL_FEED_DETAILS_SUCCESS = 'INDIVIDUAL_FEED_DETAILS_SUCCESS';
export const INDIVIDUAL_FEED_DETAILS_FAIL = 'INDIVIDUAL_FEED_DETAILS_FAIL';