export const GROUP_LIST_REQUEST = 'GROUP_LIST_REQUEST';
export const GROUP_LIST_SUCCESS = 'GROUP_LIST_SUCCESS';
export const GROUP_LIST_FAIL = 'GROUP_LIST_FAIL';

export const GROUP_CREATE_REQUEST = "GROUP_CREATE_REQUEST";
export const GROUP_CREATE_SUCCESS = "GROUP_CREATE_SUCCESS";
export const GROUP_CREATE_FAIL = "GROUP_CREATE_FAIL";
export const GROUP_CREATE_RESET = "GROUP_CREATE_RESET";

export const INDIVIDUAL_GROUP_DETAILS_REQUEST = "INDIVIDUAL_GROUP_DETAILS_REQUEST";
export const INDIVIDUAL_GROUP_DETAILS_SUCCESS = "INDIVIDUAL_GROUP_DETAILS_SUCCESS";
export const INDIVIDUAL_GROUP_DETAILS_FAIL = "INDIVIDUAL_GROUP_DETAILS_FAIL";

export const GROUP_UPDATE_REQUEST = "GROUP_UPDATE_REQUEST";
export const GROUP_UPDATE_SUCCESS = "GROUP_UPDATE_SUCCESS";
export const GROUP_UPDATE_FAIL = "GROUP_UPDATE_FAIL";
export const GROUP_UPDATE_RESET = "USER_UPDATE_RESET";

export const GROUP_DELETE_REQUEST = "GROUP_DELETE_REQUEST";
export const GROUP_DELETE_SUCCESS = "GROUP_DELETE_SUCCESS";
export const GROUP_DELETE_FAIL = "GROUP_DELETE_FAIL";

export const GROUP_JOIN_REQUEST = "GROUP_JOIN_REQUEST";
export const GROUP_JOIN_SUCCESS = "GROUP_JOIN_SUCCESS";
export const GROUP_JOIN_FAIL = "GROUP_JOIN_FAIL";
