export const RESOURCE_CATEGORY_LIST_REQUEST = 'RESOURCE_CATEGORY_LIST_REQUEST';
export const RESOURCE_CATEGORY_LIST_SUCCESS = 'RESOURCE_CATEGORY_LIST_SUCCESS';
export const RESOURCE_CATEGORY_LIST_FAIL = 'RESOURCE_CATEGORY_LIST_FAIL';
export const RESOURCE_LIST_REQUEST = 'RESOURCE_LIST_REQUEST';
export const RESOURCE_LIST_SUCCESS = 'RESOURCE_LIST_SUCCESS';
export const RESOURCE_LIST_FAIL = 'RESOURCE_LIST_FAIL';
